# Generated by Django 2.1.7 on 2019-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20190302_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('R$', 'REAL'), ('U$', 'DOLAR'), ('€', 'EURO')], default='R$', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.SmallIntegerField(choices=[(0, 'OUT'), (1, 'IN')]),
        ),
    ]
