# Generated by Django 2.1.7 on 2019-03-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20190302_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('€', 'EURO'), ('U$', 'DOLAR'), ('R$', 'REAL')], default='R$', max_length=2),
        ),
    ]
